@startuml C4_Component
title c3
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_LEFT_RIGHT()

Container(mainScript, "main.py",  "Punto de entrada")

Container_Boundary(modNotif, "Módulo de notificaciones") {
  Component(orderSys, "OrderNotificationSystem", "sistema_notificaciones.py", "Procesa el pedido y manda notificaciones")
  Component(factory, "NotificationFactory", "fabrica_notificadores.py", "Devuelve el notificador según el tipo")
  Component(emailComp, "EmailNotifier", "notificador.py", "Notificación por correo")
  Component(smsComp, "SmsNotifier", "notificador.py", "Notificación por SMS")
  Component(pushComp, "PushNotifier", "notificador.py", "Notificación push")
}

Rel(mainScript, orderSys, "Crea instancia y llama process_order")
Rel(orderSys, factory, "Pide un notificador")
Rel(factory, emailComp, "Crea cuando el tipo es email")
Rel(factory, smsComp, "Crea cuando el tipo es sms")
Rel(factory, pushComp, "Crea cuando el tipo es push")

@enduml
