@startuml C4_Component
title c3
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_LEFT_RIGHT()

Container(mainScript, "main_reportes.py",  "Punto de entrada")

Container_Boundary(modulos, "Módulo de reportes") {
  Component(reportSys, "ReportSystem", "sistema_reportes.py", "Orquesta la generación y entrega del reporte")
  Component(baseGen, "GeneradorReporte", "tipos_reporte.py", "Define la estructura general del reporte")
  Component(genVentas, "GeneradorReporteVentas", "tipos_reporte.py", "Contenido para reporte de ventas")
  Component(genInv, "GeneradorReporteInventario", "tipos_reporte.py", "Contenido para reporte de inventario")
  Component(genFin, "GeneradorReporteFinanciero", "tipos_reporte.py", "Contenido para reporte financiero")
}

Rel(mainScript, reportSys, "Crea instancia y llama generate_report")
Rel(reportSys, baseGen, "Trabaja con generadores de reporte")
Rel(reportSys, genVentas, "Usa cuando el tipo es sales")
Rel(reportSys, genInv, "Usa cuando el tipo es inventory")
Rel(reportSys, genFin, "Usa cuando el tipo es financial")

@enduml
